apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  # Replace these with your actual keys before applying
  serpapi-key: "YOUR_SERPAPI_KEY_HERE"
  groq-api-key: "YOUR_GROQ_API_KEY_HERE"